[env]
MISE_ENV = "dev"
SPRING_PROFILES_ACTIVE = "dev"
KAFKA_BOOTSTRAP = "localhost:9094"
INSURER_BASE_URL = "http://localhost:8089/submit"
JWT_SECRET = "local-dev-secret-change-me-32-bytes!!"
AUTH_DEMO_USERNAME = "demo"
AUTH_DEMO_PASSWORD = "demo-password"
